apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-03-30T19:43:55Z"
  generation: 1
  labels:
    app: survey-app
  name: survey-app
  namespace: default
  resourceVersion: "8704"
  selfLink: /apis/apps/v1/namespaces/default/deployments/survey-app
  uid: ca8385d4-72be-11ea-9b6a-42010a9600d0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: survey-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: survey-app
    spec:
      containers:
      - image: registry.hub.docker.com/hy950921/swe645hw2:1
        imagePullPolicy: IfNotPresent
        name: swe645hw2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-30T19:43:56Z"
    lastUpdateTime: "2020-03-30T19:43:56Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-30T19:43:55Z"
    lastUpdateTime: "2020-03-30T19:43:56Z"
    message: ReplicaSet "survey-app-5786d6b665" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
  
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-30T19:44:05Z"
  labels:
    app: survey-app
  name: survey-app
  namespace: default
  resourceVersion: "8900"
  selfLink: /api/v1/namespaces/default/services/survey-app
  uid: d071a213-72be-11ea-9b6a-42010a9600d0
spec:
  clusterIP: 10.39.247.255
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32590
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: survey-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.245.1.164
